version: "3"
services:
  front:
    build:
      context: ./app/src/front
      dockerfile: Dockerfile
    stdin_open: true # this line is important to keep the container running and listening
    ports:
      - "${APP_PORT}:${APP_PORT}"
    networks:
      - energy-node-app
  back:
    build:
      context: ./app/src/back
      dockerfile: Dockerfile
    ports:
      - "${API_PORT}:${API_PORT}"
    networks:
      - energy-node-app
    depends_on:
      - mongo
  mongo:
    image: mongo:3.6.19-xenial
    command: mongod --auth
    environment:
      MONGO_INTIDB_DATABASE: ${DB_NAME}
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    networks:
      - energy-node-app
    volumes:
      - mongo-data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
networks:
  energy-node-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local
