version: "3.6"

services:
  # mailpit:
  #   container_name: mailpit
  #   image: djfarrelly/maildev
  #   ports:
  #     - "1080:80"
  #     - "1025:25"
  #   networks:
  #     - energy-node-network

  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - "${NGINX_PORT}:${NGINX_PORT}"
    volumes:
      - ./app/config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./app/config/nginx/conf.d:/etc/nginx/conf.d
      - ./app/config/nginx/ssl:/etc/nginx/ssl
    networks:
      - energy-node-network

  mongodb:
    image: mongo
    restart: always
    container_name: mongodb
    ports:
      - "${MONGODB_PORT}:${MONGODB_PORT}"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    networks:
      - energy-node-network

  back:
    container_name: back
    build:
      context: ./app/src/back
      dockerfile: ./app/config/docker/Dockerfile
    ports:
      - "${API_SERVER_PORT}:${API_SERVER_PORT}"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - mongodb
    networks:
      - energy-node-network

  front:
    container_name: front
    build:
      context: ./app/src/front
      dockerfile: ./src/config/docker/Dockerfile
    depends_on:
      - back
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    networks:
      - energy-node-network

networks:
  energy-node-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
